version: "3.9"

# Variables passed to the containers
x-environment: &environment
  # Postgres DB variables
  DB_NAME: "mwa_image_plane_db"
  DB_USERNAME: "admin"
  DB_PASSWORD: "admin"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  POSTGRES_PASSWORD: "admin"

  # Django variables
  DJANGO_SECRET_KEY: "admin"
  PYTHONUNBUFFERED: 1

  # Web hosting details
  SYSTEM_ENV: "DEVELOPMENT" # DEVELOPEMENT or PRODUCTION
  WAN_IP: "146.118.70.58"
  GLEAM_URL: "mwa-image-plane.duckdns.org"

networks:
  gleam-network:
    name: gleam-network

volumes:
  uwsgi_data:
  web_static:
  web_app:
    driver: local
    driver_opts:
      type: none
      device: /home/alexmassen-hane/repos/ADACS/GleamXGPMonitoring/gleam_webapp
      o: bind

services:
  postgres:
    hostname: postgres
    container_name: postgres
    build: postgres
    user: postgres
    restart: always
    environment: *environment
    networks:
      - gleam-network
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    hostname: django
    container_name: django
    build: gleam_webapp
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment: *environment
    networks:
      - gleam-network
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/gleam_webapp/static
      - web_static:/var/www/gleam_webapp/static
      - web_app:/gleam_webapp

  nginx:
    hostname: nginx
    container_name: nginx
    build: nginx
    restart: always
    networks:
      - gleam-network
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_app:/gleam_webapp
    ports:
      - 80:80
    depends_on:
      - django
