version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./containers/Dockerfile
      target: gleamxprod
    command: >
      gunicorn gleam_webapp.wsgi:application 
        --bind 0.0.0.0:8000 
        --error-logfile /home/app/logs/gunicorn_error.log 
        --access-logfile /home/app/logs/gunicorn_access.log

    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./logs:/home/app/logs
      - ./psrcat:/home/app/web/psrcat
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "localhost:8000", "--silent"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

  db:
    build:
      context: ./containers/
      dockerfile: db.Dockerfile
      target: postgres-q3c
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  nginx:
    build: ./containers/nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all

volumes:
  postgres_data:
  static_volume:
