version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./containers/Dockerfile
      target: GleamXDev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/home/app/web/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "0.0.0.0:8000", "--silent"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

  vo:
    build:
      context: ./containers/
      dockerfile: vo.Dockerfile
      target: VOServer
    # volumes:
    #   - ./webapps:/usr/local/tomcat/webapps/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8888:8080

  db:
    build:
      context: ./containers/
      dockerfile: db.Dockerfile
      target: postgres-q3c
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  postgres_data:
