# Generated by Django 4.0.3 on 2022-05-31 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("candidate_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="gif_path",
            field=models.FileField(max_length=1024, null=True, upload_to="candidates/"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_beam",
            field=models.FloatField(blank=True, null=True, verbose_name="Primary beam value at the candidate location"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_cent_sep_deg",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Candidate seperation from observation central pointing (deg)"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_dec_deg",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate Declination (deg)"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_det_stat",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Candidate detection statistic - arbitrary value returned by filter"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_fluence",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate fluence in Jy s"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_mod_ind",
            field=models.IntegerField(blank=True, null=True, verbose_name="Candidate modulation index"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_nks_flux_rat",
            field=models.FloatField(blank=True, null=True, verbose_name="Ratio of candidate and known flux"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_nks_is_close",
            field=models.BooleanField(null=True, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_nks_sep_deg",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Separation between candidate and known in degrees"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_nks_sep_pix",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Separation between candidate and known in pixels"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_peak_flux",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate peak flux in Jy"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_ra_deg",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate Right Acension (deg)"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_rad_deg",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate radius in degrees"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_rad_pix",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate radius in pixels"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_x_pix",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate x pixel coordinate in obsevration"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="can_y_pix",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate y pixel coordinate in obsevration"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="nks_dec_deg",
            field=models.FloatField(blank=True, null=True, verbose_name="Nearest known source Declination (deg)"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="nks_dec_dms",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Nearest known source Declination (DD:MM:SS)"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="nks_det_stat",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Nearest known source detection statistic - arbitrary value returned by filter",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="nks_flux",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Nearest known source integrated flux density in Jy"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="nks_name",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Nearest known source name"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="nks_ra_deg",
            field=models.FloatField(blank=True, null=True, verbose_name="Nearest known source Right Acension (deg)"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="nks_ra_hms",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Nearest known source Right Acension (HH:MM:SS)"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="nks_res",
            field=models.FloatField(blank=True, null=True, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="nks_res_dif",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Nearest known source number of stds above mean residual"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="nks_x_pix",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Nearest known source x pixel coordinate in observation"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="nks_y_pix",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Nearest known source y pixel coordinate in observation"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="obs_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate",
                to="candidate_app.observation",
                verbose_name="Observation ID in GPS time",
            ),
        ),
    ]
