# Generated by Django 4.0.3 on 2022-05-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate_app", "0002_candidate_gif_path_alter_candidate_can_beam_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="can_cent_sep_deg",
            new_name="cent_sep_deg",
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="can_dec_dms",
            new_name="dec_dms",
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="can_nks_sep_deg",
            new_name="nks_sep_deg",
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="can_nks_sep_pix",
            new_name="nks_sep_pix",
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="can_ra_hms",
            new_name="ra_hms",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="can_dec_deg",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="can_ra_deg",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="can_rad_deg",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="can_rad_pix",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="can_x_pix",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="can_y_pix",
        ),
        migrations.AddField(
            model_name="candidate",
            name="area_pix",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate island area in pixels^2"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="dec_deg",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate island central Declination (deg)"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="ra_deg",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Candidate island central Right Acension (deg)"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="rad_deg",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate island radius in degrees"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="rad_pix",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate island radius in pixels"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="x_pix",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate island central x pixel coordinate"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="y_pix",
            field=models.FloatField(blank=True, null=True, verbose_name="Candidate island central pixel coordinate"),
        ),
    ]
