# Generated by Django 4.0.3 on 2022-06-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate_app", "0003_rename_can_cent_sep_deg_candidate_cent_sep_deg_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="filter_id",
            new_name="filter",
        ),
        migrations.AlterField(
            model_name="filter",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rating",
            name="cand_type",
            field=models.CharField(
                choices=[
                    ("T", "Transient"),
                    ("AP", "Airplane"),
                    ("RFI", "RFI"),
                    ("SL", "Sidelobe"),
                    ("A", "Alias"),
                    ("CC", "CHG Centre"),
                    ("S", "Scintillation"),
                    ("P", "Pulsar"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
