# Generated by Django 4.0.3 on 2022-06-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate_app", "0004_rename_filter_id_candidate_filter_alter_filter_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="cand_type",
            field=models.CharField(
                choices=[
                    ("T", "Transient"),
                    ("AP", "Airplane"),
                    ("RFI", "RFI"),
                    ("SL", "Sidelobe"),
                    ("A", "Alias"),
                    ("CC", "CHG Centre"),
                    ("S", "Scintillation"),
                    ("P", "Pulsar"),
                    ("O", "Other"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
