# Generated by Django 4.0.3 on 2022-07-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate_app", "0005_alter_rating_cand_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="xml_ivorns",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ivorn", models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
