# Generated by Django 4.0.3 on 2022-09-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate_app", "0006_xml_ivorns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="cand_type",
            field=models.CharField(
                choices=[
                    ("T", "Transient"),
                    ("AP", "Airplane"),
                    ("RFI", "RFI"),
                    ("SL", "Sidelobe"),
                    ("A", "Alias"),
                    ("CC", "CHG Centre"),
                    ("S", "Scintillation"),
                    ("P", "Pulsar"),
                    ("AGN", "AGN"),
                    ("D", "Drift"),
                    ("BF", "Bad Frame"),
                    ("O", "Other"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
