# Generated by Django 4.0.3 on 2022-09-05 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate_app", "0007_alter_rating_cand_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
